
CREATE TABLE IF NOT EXISTS autor(id INTEGER PRIMARY KEY AUTOINCREMENT,nombre TEXT,genero TEXT,img TEXT);

CREATE TABLE IF NOT EXISTS obra(id INTEGER PRIMARY KEY AUTOINCREMENT,titulo TEXT, autorId INTEGER);
