CREATE TABLE IF NO EXISTS proyecto (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT,genero TEXT,  img TEXT);
CREATE TABLE IF NO EXISTS personaje (id INTEGER PRIMARY KEY AUTOINCREMENT,imagen TEXT,nombre TEXT,edad INTEGER,genero TEXT,rol TEXT,proyectoid INTEGER);
CREATE TABLE IF NO EXISTS mundo (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT,paises INTEGER,razas TEXT,proyectoid );
